// <auto-generated />
namespace Shouter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_nav_property_tt_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_nav_property_tt_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201702231801084_added_nav_property_tt_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
