// <auto-generated />
namespace PizzaForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_category_to_topic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_category_to_topic));
        
        string IMigrationMetadata.Id
        {
            get { return "201702271136420_added_category_to_topic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
