// <auto-generated />
namespace CarDealer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_Log_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Log_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201703121224499_added_Log_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
