// <auto-generated />
namespace CarDealer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_FK_PartsSupplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_FK_PartsSupplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201703121123208_added_FK_PartsSupplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
