//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabloDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameType
    {
        public GameType()
        {
            this.Games = new HashSet<Game>();
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> BonusStatsId { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual Statistic Statistic { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
