// <auto-generated />
namespace StudentSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Kur : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Kur));
        
        string IMigrationMetadata.Id
        {
            get { return "201611031402453_Kur"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
